### ISSUE TITLE
项目即将正式上线了，欢迎各位收藏

### ISSUE THREAD

**Issue by jeyrce** [io-seek/ishare#1]

**Comment by newpanjing** [comment]
不错啊，哈哈~加个友链啊，我博客后台也是simpleui
QQ：599194993

**Comment by jeeyshe** [comment]
> 不错啊，哈哈~加个友链啊，我博客后台也是simpleui
> QQ：599194993

我发现这个权限还是有点问题的

**Comment by newpanjing** [comment]
最新版的修复了呀
